import { Component, OnInit } from "@angular/core";

@Component({
  selector: "app-icons",
  templateUrl: "./icons.component.html",
  styleUrls: ["./icons.component.scss"],
})
export class IconsComponent implements OnInit {
  constructor() {}

  imagesLeft = [
    "assets/img/icons/check 1.svg",
    "assets/img/icons/icn_alert-triangle.svg",
    "assets/img/icons/icn_aplications.svg",
    "assets/img/icons/icn_arrow.svg",
    "assets/img/icons/icn_arrow-left.svg",
    "assets/img/icons/icn_arrow-msg.svg",
    "assets/img/icons/icn_calendar.svg",
    "assets/img/icons/icn_cancel.svg",
    "assets/img/icons/icn_close.svg",
    "assets/img/icons/icn_cloud.svg",
    "assets/img/icons/icn_dasboard.svg",
    "assets/img/icons/icn_delete.svg",
    "assets/img/icons/icn_download.svg",
    "assets/img/icons/icn_dropdown_arrow.svg",
    "assets/img/icons/icn_edit.svg",
    "assets/img/icons/icn_file-text.svg",
    "assets/img/icons/icn_grid.svg",
    "assets/img/icons/icn_log-in.svg",
    "assets/img/icons/icn_notification.svg",
    "assets/img/icons/icn_settings.svg",
    "assets/img/icons/icn_user.svg",
  ];

  imagesRight = [
    "assets/img/icons/editor/Group.svg",
    "assets/img/icons/editor/icn_aplications(3).svg",
    "assets/img/icons/editor/icn_aplications(4).svg",
    "assets/img/icons/editor/icn_aplications(5).svg",
    "assets/img/icons/editor/icn_aplications(6).svg",
    "assets/img/icons/editor/icn_aplications(7).svg",
    "assets/img/icons/editor/icn_aplications(8).svg",
    "assets/img/icons/editor/icn_aplications(9).svg",
    "assets/img/icons/editor/icn_aplications(10).svg",
    "assets/img/icons/editor/icn_aplications(11).svg",
    "assets/img/icons/editor/icn_aplications.svg",
    "assets/img/icons/editor/Vecto(11).svg",
    "assets/img/icons/editor/Vector(3).svg",
    "assets/img/icons/editor/Vector(4).svg",
    "assets/img/icons/editor/Vector(5).svg",
    "assets/img/icons/editor/Vector(6).svg",
    "assets/img/icons/editor/Vector(7).svg",
    "assets/img/icons/editor/Vector(8).svg",
    "assets/img/icons/editor/Vector(9).svg",
    "assets/img/icons/editor/Vector(10).svg",
    "assets/img/icons/editor/Vector(12).svg",
    "assets/img/icons/editor/Vector(13).svg",
    "assets/img/icons/editor/Vector(14).svg",
    "assets/img/icons/editor/Vector(15).svg",
    "assets/img/icons/editor/Vector(16).svg",
    "assets/img/icons/editor/Vector(17).svg",
    "assets/img/icons/editor/Vector(18).svg",
    "assets/img/icons/editor/Vector(19).svg",
    "assets/img/icons/editor/Vector(20).svg",
    "assets/img/icons/editor/Vector(21).svg",
    "assets/img/icons/editor/Vector(22).svg",
    "assets/img/icons/editor/Vector(23).svg",
    "assets/img/icons/editor/Vector(24).svg",
    "assets/img/icons/editor/Vector(25).svg",
    "assets/img/icons/editor/Vector(26).svg",
    "assets/img/icons/editor/Vector(27).svg",
    "assets/img/icons/editor/Vector(28).svg",
    "assets/img/icons/editor/Vector(29).svg",
    "assets/img/icons/editor/Vector(30).svg",
    "assets/img/icons/editor/Vector(31).svg",
    "assets/img/icons/editor/Vector(32).svg",
    "assets/img/icons/editor/Vector(33).svg",
    "assets/img/icons/editor/Vector(34).svg",
    "assets/img/icons/editor/Vector(35).svg",
    "assets/img/icons/editor/Vector(36).svg",
    "assets/img/icons/editor/Vector(37).svg",
    "assets/img/icons/editor/Vector(38).svg",
    "assets/img/icons/editor/Vector(39).svg",
    "assets/img/icons/editor/Vector(40).svg",
    "assets/img/icons/editor/Vector(41).svg",
    "assets/img/icons/editor/Vector(42).svg",
    "assets/img/icons/editor/Vector(43).svg",
    "assets/img/icons/editor/Vector(44).svg",
    "assets/img/icons/editor/Vector(45).svg",
    "assets/img/icons/editor/Vector(46).svg",
    "assets/img/icons/editor/Vector(47).svg",
    "assets/img/icons/editor/Vector(48).svg",
    "assets/img/icons/editor/Vector(49).svg",
    "assets/img/icons/editor/Vector(50).svg",
    "assets/img/icons/editor/Vector(51).svg",
  ];

  ngOnInit() {}
}
